/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

version = "0.2-20240523"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

//    implementation("org.apache.poi:poi:4.1.2")
    implementation("org.apache.poi:poi-ooxml:5.2.3")
//    implementation("org.apache.poi:poi-ooxml-schemas:4.1.2")
    implementation("org.apache.xmlbeans:xmlbeans:5.1.1")
    implementation("org.apache.logging.log4j:log4j-api:2.23.0")
    implementation("org.apache.logging.log4j:log4j-core:2.23.0")

//    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
//    implementation("com.fasterxml.jackson.core:jackson-core:2.16.2")
//    implementation("com.fasterxml.jackson.core:jackson-databind:2.16.2")
//    implementation("com.fasterxml.jackson.core:jackson-annotations:2.16.2")
//    implementation("org.openapitools:jackson-databind-nullable:0.2.1")
//    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.16.2")
//    implementation("com.fasterxml.jackson.datatype:jackson-datatype-joda:2.16.2")


}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.jacekkowalczyk82.docx.tools.DocxFixApp"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
